---
- hosts: webservers
  tasks:
    - name: install apache2
      apt: name=apache2 update_cache=yes state=latest

    - name: public_html kataloogi loomine userile
      file:
       path=/home/user/public_html
       owner=user
       group=user
       mode=0755
       state=directory

    - name: userdir mod lubamine
      apache2_module: name=userdir state=present

    - name: Apache2 serveri restartimine
      service:
       name: apache2
       state: restarted

    - name: index.html faili kopeerimine userile public_html kataloogi
      copy:
       src: /var/www/html/index.html
       dest: /home/user/public_html/
       remote_src: yes
       owner: user
       group: user

    - name: index.html faili redigeerimine
      lineinfile: dest=/home/user/public_html/index.html regexp="Apache2 Debian Default Page" line="USERI LEHEKYLG" state=present

    - name: Apache2 serveri restartimine
      service:
       name: apache2
       state: restarted
