---
- hosts: webservers
  tasks:
  - name: Allalaadimiste kataloogi loomine
    file:
     path=/root/allalaadimised
     owner=root
     group=root
     mode=0755
     state=directory

  - name: mysql repositooriumi paketti allalaadimine apt-i lisamiseks
    get_url:
     url: http://repo.mysql.com/mysql-apt-config_0.8.24-1_all.deb
     dest: "/root/allalaadimised"
     mode: 0440

  - name: mysql repositooriumi installeerimine
    apt: "deb=/root/allalaadimised/mysql-apt-config_0.8.24-1_all.deb"

  - name: mysql installeerimine
    apt: name=mysql-server update_cache=yes state=present
